config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root  to: 'home_page#index'

  scope module: :users do
    resources :tickets, only: [:create, :show]
  end

  namespace :users do
    resources :tickets, only: [] do
       resources :replies, only: [:create], namespace: :users
    end
  end

  scope module: :staff do
    resources :dashboard, only: [:index]
    resources :search, only: [:create]
    resources :tickets, only: [] do
      resources :replies, only: [:new, :create]
    end
  end

end

app/models/department.rb
class Department < ActiveRecord::Base

  validates :name, presence: true
  has_one :ticket
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket
end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  belongs_to :ticket
  has_attached_file :image, :styles => { thumb: '100x100' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :name, presence: true
  has_one :ticket

  STATUSES = ["Waiting for Staff Response", "Waiting for Customer",
              "On Hold", "Cancelled", "Completed"]

  CLOSED_STATUSES = ['Cancelled', 'Completed']
  OPEN_STATUSES = ['Waiting for Staff Response', 'Waiting for Customer']
  HOLD_STATUSES = ['On Hold']

  scope :closed, -> { where('name IN (?)', CLOSED_STATUSES) }
  scope :open, -> { where('name IN (?)', OPEN_STATUSES) }
  scope :hold, -> { where('name IN (?)', HOLD_STATUSES) }
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  before_create :generate_reference
  has_one :screenshot
  belongs_to :department
  belongs_to :status
  belongs_to :user
  has_many :replies
  has_many :tracks

  validates :body, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :department, presence: true
  validates :status, presence: true

  DEFAULT_STATUS = 'Waiting for Staff Response'

  scope :closed, -> { joins(:status).merge(Status.closed) }
  scope :open, -> { joins(:status).merge(Status.open) }
  scope :hold, -> { joins(:status).merge(Status.hold) }

  def to_param
    reference
  end

  def self.search(str)
    return [] if str.blank?

    cond_text   = str.split.map{|w| "body LIKE ? "}.join(" OR ")
    cond_values = str.split.map{|w| "%#{w}%"}
    where(str ? [cond_text, *cond_values] : [])
  end

  private
  def generate_reference
    reference = [ random_str('A'..'Z'), random_str('0'..'9'),
                  random_str('A'..'Z'), random_str('0'..'9'),
                  random_str('A'..'Z') ].join('-')
    self.reference = reference
  end

  def random_str(range, length = 3)
    return '' if length < 1 || range.count < length

    range.to_a.shuffle[0, length].join()
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :ticket
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
  has_many :tickets
  has_many :replies
  # test push event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @ticket = Ticket.new
    @departments = Department.all
  end
end

app/controllers/staff/base_controller.rb
class Staff::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/staff/dashboard_controller.rb
class Staff::DashboardController < Staff::BaseController

  def index
    @open_tickets = Ticket.includes(:department).open
    @hold_tickets = Ticket.includes(:department).hold
    @closed_tickets = Ticket.includes(:department).closed
  end

end

app/controllers/staff/replies_controller.rb
class Staff::RepliesController < Staff::BaseController
  respond_to :js
  before_filter :find_ticket

  def new
    @staff = User.all
  end

  def create
    status = Status.where(name: params[:status]).first
    staff = User.where(email: params[:staff]).first
    attrs_hash = {}
    attrs_hash.merge!(status: status) if status
    attrs_hash.merge!(user: staff) if staff
    build_staff_reply if params[:staff_reply].present?
    build_track(status, staff)
    if @ticket.update_attributes(attrs_hash)
      UserMailer.new_reply(@ticket).deliver
      flash.now[:success] = 'Reply was successfully created'
      render :create_success
    else
      flash.now[:error] = @ticket.errors.full_messages.to_sentence
      render :create_error
    end
  end

  private

  def find_ticket
    @ticket = Ticket.where(reference: params[:ticket_id]).first
  end

  def build_staff_reply
    @ticket.replies.build(body: params[:staff_reply], user: current_user)
  end

  def build_track(status, staff)
    @ticket.tracks.build(status: !!status,
                         staff: !!staff,
                         reply: params[:staff_reply].present?)
  end

end

app/controllers/staff/search_controller.rb
class Staff::SearchController < Staff::BaseController
  def create
    @ticket_by_reference = Ticket.where(reference: params[:search_reference])
    @tickets_by_words = Ticket.search(params[:search_word])
    @result = @ticket_by_reference + @tickets_by_words
    flash.now[:success] = 'Search is complete!'
  end
end

app/controllers/users/replies_controller.rb
class Users::RepliesController < ApplicationController
  def create
    @ticket = Ticket.where(reference: params[:ticket_id]).first
    @ticket.replies.build(body: params[:user_reply], user: nil)
    if @ticket.save
      flash.now[:success] = 'Reply was successfully created'
    else
      flash.now[:error] = @ticket.errors.full_messages.to_sentence
    end
  end
end

app/controllers/users/tickets_controller.rb
class Users::TicketsController < ApplicationController
  respond_to :js

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.status = Status.where(name: Ticket::DEFAULT_STATUS ).first
    build_screenshot(@ticket)
    if @ticket.save
      UserMailer.new_ticket(@ticket).deliver
      flash[:success] = 'Your ticket has been successfully submitted'
      render 'create_success'
    else
      flash.now[:error] = %Q{The following errors prevent your ticket submission:
                             #{@ticket.errors.full_messages.to_sentence}}

      render 'create_error'
    end
  end

  def show
    @ticket = Ticket.where(:reference => params[:id]).includes(:replies).first
    unless @ticket
      flash[:error] = 'Ticket not found'
      redirect_to root_url
    end
  end

  private

  def ticket_params
      params.require(:ticket).permit(:body, :email, :department_id)
  end

  def build_screenshot(ticket)
    if params[:ticket][:screenshot]
      ticket.build_screenshot(image: params[:ticket][:screenshot])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class_name(name)
    case name
      when :notice then 'info'
      when :success then 'success'
      when :error then 'danger'
    else
      'warning'
    end
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/staff/replies_helper.rb
module Staff::RepliesHelper
  def staff_list(list)
    list.map(&:email)
  end
end

app/helpers/users/tickets_helper.rb
module Users::TicketsHelper
  def staff_assigned(ticket)
    ticket.user.try(:email) || 'unassigned'
  end
end

app/views/home_page/index.html.slim
h3 Welcome to HelpDesk System!
p Please, submit your issue
.issue-form
  = form_for @ticket, remote: true, authenticity_token: true, multipart: true do |f|

    .form-group
      = f.label :body, 'Issue'
      = f.text_area :body, cols: 30, rows: 10, placeholder: 'Describe your issue', class: 'form-control'
    .form-group
      .row
        .col-md-1= f.label :email, 'Email'
        .col-md-11= f.text_field :email
    .from-group
      .row
        .col-md-1= f.label :department, 'Department'
        .col-md-11= f.collection_select(:department_id, @departments, :id, :name, include_blank: "Please select")
    .form-group
      = f.label :screenshot, 'Upload screenshot'
      = f.file_field :screenshot, id: 'fileupload'
    .honeypot= text_field_tag :honeypot
    = f.submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title Helpdesk
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #flash-block= render 'layouts/shared/messages'
    = render 'layouts/shared/navbar'
    .container= yield

app/views/layouts/shared/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="flash-messages-block alert alert-#{flash_class_name(name.to_sym)}"
      a.close data-dismiss='alert' ×
      = content_tag :div, msg, :class => "flash flash_#{name}"
javascript:
  setTimeout( function(){
    $('.flash-messages-block').fadeOut(3000);
  }, 5000 );

app/views/layouts/shared/_navbar.html.slim
nav.navbar.navbar-default.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      = link_to 'HELPDESK SYSTEM', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li= link_to 'DASHBOARD', dashboard_index_path
          li= link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          li= link_to 'Sign In', new_user_session_path

app/views/staff/dashboard/_tickets_list.html.slim
table.table.table-striped
  thead
    tr
      th #
      th Reference
      th Department
      th Status
      th Email
      th Staff
      th Reply
  tbody
    - tickets.each_with_index do |ticket, num|
      tr
        th= num + 1
        th= ticket.reference
        th= ticket.department.name
        th= ticket.status.name
        th= mail_to ticket.email
        th= staff_assigned(ticket)
        th= link_to 'reply', new_ticket_reply_path(ticket), remote: true

app/views/staff/dashboard/index.html.slim
h3 TICKETS LIST

ul.nav.nav-tabs#tabs role='tablist'
  li.active= link_to 'Open', '#open', role: 'tab', data: {toggle: 'tab'}
  li= link_to 'Hold', '#hold', role: 'tab', data: {toggle: 'tab'}
  li= link_to 'Closed', '#closed', role: 'tab', data: {toggle: 'tab'}
  li= link_to 'Search', '#search', role: 'tab', data: {toggle: 'tab'}
#my-tab-content.tab-content
  #open.tab-pane.active= render 'tickets_list', tickets: @open_tickets
  #hold.tab-pane= render 'tickets_list', tickets: @hold_tickets
  #closed.tab-pane= render 'tickets_list', tickets: @closed_tickets
  #search.tab-pane= render 'staff/search/search'

app/views/staff/replies/_reply.html.slim
.reply-dialog.modal
  .modal-dialog
    .modal-content
      .modal-header
        .close.pull-right data-dismiss='tab'
          = "&times".html_safe
        h4.modal-title Reply to user
      .modal-body
        = form_for ticket, url: ticket_replies_path(ticket), method: :post, remote: true do |f|
          .ticket-body
            .header Ticket content
            .body= f.object.body
            - if f.object.screenshot
              .image=link_to image_tag(f.object.screenshot.image.url(:thumb)), f.object.screenshot.image.url(:original)
            - if ticket.replies.any?
              .replies
                | List of replies
                ul
                  - ticket.replies.each do |reply|
                    li.reply= reply.body
            .status.row
              .col-md-4 Select New Status
              .col-md-8= select_tag :status, options_for_select(Status::STATUSES), include_blank: true
            .owner.row
              .col-md-4 Select Owner
              .col-md-8= select_tag :staff, options_for_select(staff_list(@staff)), include_blank: true
            .reply.row
              .col-md-4= 'Enter your reply'
              .col-md-8= text_area_tag :staff_reply
      .modal-footer
        button.btn.btn-default type='button' data-dismiss='modal' Cancel
        button.btn.btn-success.modal-form-submit type='button' Send

app/views/staff/replies/create_error.js.erb
$('#flash-block').append("<%= escape_javascript render('layouts/shared/messages') %>");

app/views/staff/replies/create_success.js.erb
$('#flash-block').append("<%= escape_javascript render('layouts/shared/messages') %>");
$('.reply-dialog').modal('hide').remove();
window.location.href = '<%= dashboard_index_path %>';

app/views/staff/replies/new.js.erb
$('body').find('.reply-dialog').hide().remove();
$('body').append("<%= escape_javascript render('reply', ticket: @ticket) %>");
$('body').find('.reply-dialog').modal('show');

app/views/staff/search/_search.html.slim
= form_for :search, url: search_index_path, method: :post, remote: true
  .row
    .col-md-4 Search by reference
    .col-md-8= text_field_tag :search_reference
  .row
    .col-md-12 Or
  .row
    .col-md-4 Search by words
    .col-md-8 = text_field_tag :search_word
  = submit_tag 'Search'
.results

app/views/staff/search/create.js.erb
$('#flash-block').append("<%= escape_javascript render('layouts/shared/messages') %>");
$('.results').html("<%= escape_javascript render('staff/dashboard/tickets_list', tickets: @result) %>");

app/views/users/replies/create.js.erb
$('#flash-block').append("<%= escape_javascript render('layouts/shared/messages') %>")

app/views/users/tickets/create_error.js.erb
$('#flash-block').append("<%= escape_javascript render('layouts/shared/messages') %>")

app/views/users/tickets/create_success.js.erb
window.location.href = '<%= root_path %>';

app/views/users/tickets/show.html.slim
h3 Please, review the ticket
.row
  .col-md-12
    .user-ticket
      .body
        = @ticket.body
      .replies
        | List of replies
        ul
          - @ticket.replies.each do |reply|
            li.reply= reply.body
      .add-reply
        = form_for @ticket, url: users_ticket_replies_path(@ticket), method: :post, remote: true do |f|
          .reply.row
            .col-md-2= 'Enter your reply'
            .col-md-10= text_area_tag :user_reply
          = f.submit 'Post reply'